title                   : My awesome site 1
repo                    : https://github.com
version                 : 0.0.0
src                     : /Users/rodleviton/Dev/swanky-cli/__fixtures__/mock-site/sites/my-awesome-site-1-theme/src
theme                   : /Users/rodleviton/Dev/swanky-cli/__fixtures__/mock-site/sites/my-awesome-site-1-theme/src/themes/my-awesome-site-1-theme
output                  : /Users/rodleviton/Dev/swanky-cli/__fixtures__/mock-site/sites/my-awesome-site-1-theme/build
snippets                : /Users/rodleviton/Dev/swanky-cli/__fixtures__/mock-site/sites/my-awesome-site-1-theme/src/snippets

sections                :

  - title               : Overview
    content             : '/Users/rodleviton/Dev/swanky-cli/__fixtures__/mock-site/sites/my-awesome-site-1-theme/src/content/overview.md'
